In [1]:
import pandas as pd
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import plotly.express as px
import plotly.graph_objs as go
from sklearn.metrics import f1_score, recall_score, precision_score, mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [2]:
df = pd.DataFrame(pd.read_excel('C:\\Users\\gaszk\\Documents\\KAR\\SKRIPSHIT\\data\\BIGFIVE.xlsx'))
df.to_csv('BIGFIVE.csv', index = None, header = True)

In [3]:
df

Nama  Danceability    Energy  Speechiness  \
0                      BIMA      0.564429  0.867000     0.065052   
1                     GALIH      0.640451  0.748083     0.073577   
2                      DIVA      0.593477  0.548761     0.050318   
3                    NISPUR      0.582821  0.562268     0.053425   
4                      SUNU      0.521280  0.647800     0.035584   
..                      ...           ...       ...          ...   
196                NURLIANA      0.572567  0.590767     0.057467   
197              Syahrul 21      0.573233  0.567933     0.053863   
198  Azzahra Ghina Lutfiani      0.494367  0.482267     0.033080   
199        Fatimah Az Zahra      0.643600  0.565450     0.072705   
200          Dewi Arthasari      0.522133  0.407067     0.033727   

     Acousticness  Instrumetalness  Liveness   Valence       Tempo   e   a  \
0        0.066338         0.003463  0.295398  0.606595  142.703738  28  31   
1        0.147558         0.051822  0.189778  0.480346  127.574218  22  29   
2        0.415290         0.030824  0.159370  0.514500  110.935409  13  25   
3        0.379153         0.005340  0.167027  0.418779  120.543518  35  39   
4        0.241890         0.043464  0.138768  0.522560  124.434640   9  25   
..            ...              ...       ...       ...         ...  ..  ..   
196      0.286244         0.000112  0.176493  0.431833  134.592000  15  23   
197      0.357294         0.008958  0.167013  0.399730  123.068967   9  29   
198      0.574472         0.036431  0.156077  0.340237  128.072900   5  26   
199      0.326633         0.000364  0.130260  0.466685  119.251550  14  23   
200      0.706773         0.038620  0.114550  0.394770  114.192933  18  28   

      c   n   o  Angkatan  
0    29  33  30        18  
1    21  22  39        18  
2    19  21  20        18  
3    20  30  29        18  
4    23  23  23        18  
..   ..  ..  ..       ...  
196  24  17  23        21  
197  25  23  28        21  
198  24  10  25        21  
199  26  21  29        21  
200  19  20  21        21  

[201 rows x 15 columns]

In [55]:
df4['Acousticness'] = df4['Acousticness'].astype('float16')
df4['Speechiness'] = df4['Speechiness'].astype('float16')
df4['Danceability'] = df4['Danceability'].astype('float16')
df4['Energy'] = df4['Energy'].astype('float16')
df4['Instrumetalness'] = df4['Instrumetalness'].astype('float16')
df4['Valence'] = df4['Valence'].astype('float16')
df4['Liveness'] = df4['Liveness'].astype('float16')
df4['e'] = df4['e'].astype(np.uint8)
df4['a'] = df4['a'].astype(np.uint8)
df4['c'] = df4['c'].astype(np.uint8)
df4['n'] = df4['n'].astype(np.uint8)
df4['o'] = df4['o'].astype(np.uint8)

In [57]:
df4.info()(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Acousticness     201 non-null    float16
 1   Danceability     201 non-null    float16
 2   Energy           201 non-null    float16
 3   Instrumetalness  201 non-null    float16
 4   Valence          201 non-null    float16
 5   Liveness         201 non-null    float16
 6   Speechiness      201 non-null    float16
 7   e                201 non-null    uint8  
 8   a                201 non-null    uint8  
 9   c                201 non-null    uint8  
 10  n                201 non-null    uint8  
 11  o                201 non-null    uint8  
dtypes: float16(7), uint8(5)
memory usage: 3.9 KB


TypeError: 'NoneType' object is not callable

In [67]:
y1 = df4.iloc[:, -1]
y1

0      30
1      39
2      20
3      29
4      23
       ..
196    23
197    28
198    25
199    29
200    21
Name: o, Length: 201, dtype: int64

In [39]:
df4 = df[['Acousticness','Danceability','Energy', 'Instrumetalness', 'Valence','Liveness','Speechiness','Tempo','e','a','c' ,'n' ,'o']]

In [40]:
X = df4.iloc[:, 1:-6]
y1 = df4.iloc[:, -1]
X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y1_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

Best parameters found:  {'bootstrap': False, 'criterion': 'poisson', 'max_depth': 6, 'max_features': None, 'max_samples': 1, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100, 'warm_start': True}
Best score found:  -3.5955437834224613


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan ... -3.7761235 -3.7761235 -3.7761235]
  warnings.warn(


In [41]:
best_model = grid_search.best_estimator_
y1_pred = best_model.predict(X_test)
y1_pred

array([22.72941176, 22.72941176, 22.72941176, 22.72941176, 22.72941176,
       22.72941176, 22.72941176, 22.72941176, 22.72941176, 22.72941176,
       22.72941176, 22.72941176, 22.72941176, 22.72941176, 22.72941176,
       22.72941176, 22.72941176, 22.72941176, 22.72941176, 22.72941176,
       22.72941176])

In [42]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y1_test, y1_pred))

# Calculate the MAE
mae = mean_absolute_error(y1_test, y1_pred)

# Calculate R-squared
r2 = r2_score(y1_test, y1_pred)

#MAPE
mape = mean_absolute_error(y1_test, y1_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 3.69204566417547
MAE: 3.0823529411764703
R-squared: -0.030401049568629768
MAPE: 308.235294117647


In [43]:
X = df4.iloc[:, 1:-6]
y2 = df4.iloc[:, -2]
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True,False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y2_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -6.1842957  -6.18212917
 -6.18212917]
  warnings.warn(


Best parameters found:  {'bootstrap': False, 'criterion': 'friedman_mse', 'max_depth': 4, 'max_features': 'sqrt', 'max_samples': 1, 'min_samples_leaf': 2, 'min_samples_split': 6, 'n_estimators': 300, 'warm_start': True}
Best score found:  -5.577526212015955


In [44]:
best_model = grid_search.best_estimator_
y2_pred = best_model.predict(X_test)
y2_pred

array([17.23353517, 18.24100986, 18.27301412, 16.64332252, 17.41609607,
       15.68946647, 13.34050501, 16.86885252, 17.05038888, 16.96924957,
       15.99176136, 18.22234948, 15.83250262, 17.65687191, 17.2709053 ,
       17.28935977, 14.86082864, 15.94397514, 16.0055414 , 17.38309236,
       17.13462416])

In [45]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y2_test, y2_pred))

# Calculate the MAE
mae = mean_absolute_error(y2_test, y2_pred)

# Calculate R-squared
r2 = r2_score(y2_test, y2_pred)

#MAPE
mape = mean_absolute_error(y2_test, y2_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 5.167739766400052
MAE: 4.377154311184837
R-squared: 0.006148470606285428
MAPE: 437.7154311184837


In [46]:
X = df4.iloc[:, 1:-6]
y3 = df4.iloc[:, -3]
X_train, X_test, y3_train, y3_test = train_test_split(X, y3, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y3_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -4.9814401  -4.98012945
 -4.98012945]
  warnings.warn(


Best parameters found:  {'bootstrap': True, 'criterion': 'friedman_mse', 'max_depth': 4, 'max_features': 'sqrt', 'max_samples': 4, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300, 'warm_start': True}
Best score found:  -4.41975


In [47]:
best_model = grid_search.best_estimator_
y3_pred = best_model.predict(X_test)
y3_pred

array([25.37      , 25.32666667, 24.79      , 25.01333333, 25.77      ,
       25.4       , 25.46      , 25.77333333, 25.83      , 25.26333333,
       25.96333333, 24.91333333, 25.67333333, 25.17333333, 25.42      ,
       25.47666667, 24.92333333, 26.00333333, 25.45      , 24.77      ,
       24.45666667])

In [48]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y3_test, y3_pred))

# Calculate the MAE
mae = mean_absolute_error(y3_test, y3_pred)

# Calculate R-squared
r2 = r2_score(y3_test, y3_pred)

#MAPE
mape = mean_absolute_error(y3_test, y3_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 5.672662374291142
MAE: 4.6742857142857135
R-squared: 0.05241837606837585
MAPE: 467.42857142857133


In [49]:
X = df4.iloc[:, 1:-6]
y4 = df4.iloc[:, -4]
X_train, X_test, y4_train, y4_test = train_test_split(X, y4, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y4_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

Best parameters found:  {'bootstrap': True, 'criterion': 'friedman_mse', 'max_depth': 4, 'max_features': 'sqrt', 'max_samples': 1, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100, 'warm_start': True}
Best score found:  -3.809666666666667


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -4.31430724 -4.31405261
 -4.31405261]
  warnings.warn(


In [50]:
best_model = grid_search.best_estimator_
y4_pred = best_model.predict(X_test)
y4_pred

array([26.73, 26.73, 26.73, 26.73, 26.73, 26.73, 26.73, 26.73, 26.73,
       26.73, 26.73, 26.73, 26.73, 26.73, 26.73, 26.73, 26.73, 26.73,
       26.73, 26.73, 26.73])

In [51]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y4_test, y4_pred))

# Calculate the MAE
mae = mean_absolute_error(y4_test, y4_pred)

# Calculate R-squared
r2 = r2_score(y4_test, y4_pred)

#MAPE
mape = mean_absolute_error(y4_test, y4_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 5.603786559954243
MAE: 4.030952380952382
R-squared: -0.18342752520936578
MAPE: 403.0952380952382


In [52]:
X = df4.iloc[:, 1:-6]
y5 = df4.iloc[:, -5]
X_train, X_test, y5_train, y5_test = train_test_split(X, y5, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y5_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

Best parameters found:  {'bootstrap': True, 'criterion': 'friedman_mse', 'max_depth': 4, 'max_features': 'sqrt', 'max_samples': 2, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100, 'warm_start': True}
Best score found:  -5.060388888888889


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -5.42262387 -5.42488653
 -5.42488653]
  warnings.warn(


In [53]:
best_model = grid_search.best_estimator_
y5_pred = best_model.predict(X_test)
y5_pred

array([16.3 , 16.95, 15.92, 16.49, 16.57, 16.13, 16.46, 16.22, 16.07,
       16.57, 16.38, 16.33, 16.33, 16.02, 16.7 , 16.44, 16.25, 16.44,
       16.57, 16.58, 16.23])

In [54]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y5_test, y5_pred))

# Calculate the MAE
mae = mean_absolute_error(y5_test, y5_pred)

# Calculate R-squared
r2 = r2_score(y5_test, y5_pred)

#MAPE
mape = mean_absolute_error(y5_test, y5_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 6.123363143769623
MAE: 5.000476190476191
R-squared: -0.02285964988246958
MAPE: 500.0476190476191


In [24]:
df3 = np.abs(df4[['Acousticness','Danceability','Energy','Instrumetalness', 'Valence', 'Liveness', 'Speechiness','Tempo']] - df4[['Acousticness','Danceability','Energy','Instrumetalness', 'Valence', 'Liveness', 'Speechiness','Tempo']].mean())<=(2*df4[['Acousticness','Danceability','Energy','Instrumetalness', 'Valence', 'Liveness', 'Speechiness','Tempo']].std())
print(df3.shape)
df3.head()

(201, 8)


Acousticness  Danceability  Energy  Instrumetalness  Valence  Liveness  \
0          True          True   False             True     True     False   
1          True          True    True             True     True      True   
2          True          True    True             True     True      True   
3          True          True    True             True     True      True   
4          True          True    True             True     True      True   

   Speechiness  Tempo  
0         True  False  
1         True   True  
2         True   True  
3         True   True  
4         True   True

In [55]:
df2 = df4[df3.Acousticness & df3.Danceability & df3.Energy & df3.Instrumetalness	 & df3.Valence	& df3.Liveness	& df3.Speechiness &df3.Tempo]

In [56]:
X = df2.iloc[:, 1:-6]
y1 = df2.iloc[:, -1]
X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y1_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -3.99797791 -3.99797236
 -3.99797236]
  warnings.warn(


Best parameters found:  {'bootstrap': True, 'criterion': 'friedman_mse', 'max_depth': 4, 'max_features': 'sqrt', 'max_samples': 4, 'min_samples_leaf': 1, 'min_samples_split': 6, 'n_estimators': 300, 'warm_start': True}
Best score found:  -3.6025010752688176


In [57]:
best_model = grid_search.best_estimator_
y1_pred = best_model.predict(X_test)
y1_pred

array([22.84416667, 22.84416667, 22.84416667, 22.84416667, 22.84416667,
       22.84416667, 22.84416667, 22.84416667, 22.84416667, 22.84416667,
       22.84416667, 22.84416667, 22.84416667, 22.84416667, 22.84416667,
       22.84416667, 22.84416667])

In [58]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y1_test, y1_pred))

# Calculate the MAE
mae = mean_absolute_error(y1_test, y1_pred)

# Calculate R-squared
r2 = r2_score(y1_test, y1_pred)

#MAPE
mape = mean_absolute_error(y1_test, y1_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 4.9983006630227695
MAE: 3.9686764705882354
R-squared: -0.05649542737700375
MAPE: 396.86764705882354


In [59]:
X = df2.iloc[:, 1:-6]
y2 = df2.iloc[:, -2]
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y2_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

Best parameters found:  {'bootstrap': False, 'criterion': 'poisson', 'max_depth': 6, 'max_features': 'sqrt', 'max_samples': 1, 'min_samples_leaf': 2, 'min_samples_split': 6, 'n_estimators': 100, 'warm_start': True}
Best score found:  -5.449875567655718


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -5.72590129 -5.72652172
 -5.72652172]
  warnings.warn(


In [60]:
best_model = grid_search.best_estimator_
y2_pred = best_model.predict(X_test)
y2_pred

array([17.09481901, 16.22101328, 17.09253932, 16.71753932, 21.14961111,
       19.87995346, 16.23461534, 17.30198869, 18.1496307 , 16.22101328,
       16.22101328, 16.27309995, 16.22101328, 16.22101328, 16.22101328,
       16.22101328, 16.22101328])

In [61]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y2_test, y2_pred))

# Calculate the MAE
mae = mean_absolute_error(y2_test, y2_pred)

# Calculate R-squared
r2 = r2_score(y2_test, y2_pred)

#MAPE
mape = mean_absolute_error(y2_test, y2_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 6.971284633225604
MAE: 5.835960951604875
R-squared: -0.10817862769625286
MAPE: 583.5960951604875


In [62]:
X = df2.iloc[:, 1:-6]
y3 = df2.iloc[:, -3]
X_train, X_test, y3_train, y3_test = train_test_split(X, y3, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y3_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

Best parameters found:  {'bootstrap': True, 'criterion': 'friedman_mse', 'max_depth': 4, 'max_features': None, 'max_samples': 4, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100, 'warm_start': True}
Best score found:  -4.620382795698925


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -5.13802373 -5.13492757
 -5.13492757]
  warnings.warn(


In [63]:
best_model = grid_search.best_estimator_
y3_pred = best_model.predict(X_test)
y3_pred

array([24.53, 24.27, 25.86, 25.48, 25.88, 25.31, 24.39, 25.59, 25.96,
       24.04, 25.6 , 24.44, 25.3 , 24.35, 25.04, 25.03, 24.96])

In [64]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y3_test, y3_pred))

# Calculate the MAE
mae = mean_absolute_error(y3_test, y3_pred)

# Calculate R-squared
r2 = r2_score(y3_test, y3_pred)

#MAPE
mape = mean_absolute_error(y3_test, y3_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 4.6978587112202765
MAE: 3.49
R-squared: -0.0038077274158010432
MAPE: 349.0


In [65]:
X = df2.iloc[:, 1:-6]
y4 = df2.iloc[:, -4]
X_train, X_test, y4_train, y4_test = train_test_split(X, y4, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y4_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -4.37048288 -4.37025062
 -4.37025062]
  warnings.warn(


Best parameters found:  {'bootstrap': True, 'criterion': 'poisson', 'max_depth': 4, 'max_features': None, 'max_samples': 7, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200, 'warm_start': True}
Best score found:  -3.771194713261649


In [66]:
best_model = grid_search.best_estimator_
y4_pred = best_model.predict(X_test)
y4_pred

array([27.75633333, 26.12716667, 26.94583333, 27.71216667, 28.51916667,
       27.55166667, 27.313     , 27.60883333, 27.87383333, 26.55      ,
       26.51916667, 27.0625    , 25.9375    , 27.07216667, 27.4325    ,
       26.73083333, 26.42583333])

In [67]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y4_test, y4_pred))

# Calculate the MAE
mae = mean_absolute_error(y4_test, y4_pred)

# Calculate R-squared
r2 = r2_score(y4_test, y4_pred)

#MAPE
mape = mean_absolute_error(y4_test, y4_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 7.331726614649566
MAE: 5.249264705882354
R-squared: -0.15415811136082236
MAPE: 524.9264705882354


In [31]:
df2

Acousticness  Danceability    Energy  Instrumetalness   Valence  \
1        0.147558      0.640451  0.748083         0.051822  0.480346   
2        0.415290      0.593477  0.548761         0.030824  0.514500   
3        0.379153      0.582821  0.562268         0.005340  0.418779   
4        0.241890      0.521280  0.647800         0.043464  0.522560   
5        0.528306      0.479194  0.435694         0.000304  0.417942   
..            ...           ...       ...              ...       ...   
196      0.286244      0.572567  0.590767         0.000112  0.431833   
197      0.357294      0.573233  0.567933         0.008958  0.399730   
198      0.574472      0.494367  0.482267         0.036431  0.340237   
199      0.326633      0.643600  0.565450         0.000364  0.466685   
200      0.706773      0.522133  0.407067         0.038620  0.394770   

     Liveness  Speechiness       Tempo   e   a   c   n   o  
1    0.189778     0.073577  127.574218  22  29  21  22  39  
2    0.159370     0.050318  110.935409  13  25  19  21  20  
3    0.167027     0.053425  120.543518  35  39  20  30  29  
4    0.138768     0.035584  124.434640   9  25  23  23  23  
5    0.187475     0.086022  120.884889  13  21  20  15  24  
..        ...          ...         ...  ..  ..  ..  ..  ..  
196  0.176493     0.057467  134.592000  15  23  24  17  23  
197  0.167013     0.053863  123.068967   9  29  25  23  28  
198  0.156077     0.033080  128.072900   5  26  24  10  25  
199  0.130260     0.072705  119.251550  14  23  26  21  29  
200  0.114550     0.033727  114.192933  18  28  19  20  21  

[169 rows x 13 columns]

In [68]:
X = df2.iloc[:, 1:-6]
y5 = df2.iloc[:, -5]
X_train, X_test, y5_train, y5_test = train_test_split(X, y5, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True, False],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [True, False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y5_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [        nan         nan         nan ... -5.15911529 -5.15883083
 -5.15883083]
  warnings.warn(


Best parameters found:  {'bootstrap': False, 'criterion': 'poisson', 'max_depth': 6, 'max_features': 'sqrt', 'max_samples': 1, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 100, 'warm_start': True}
Best score found:  -5.082783472360912


In [69]:
best_model = grid_search.best_estimator_
y5_pred = best_model.predict(X_test)
y5_pred

array([15.22401386, 15.1077663 , 15.1077663 , 15.30276386, 21.52621429,
       20.21702645, 15.1077663 , 17.57348293, 17.97960298, 16.85733516,
       15.1077663 , 20.4088637 , 15.1077663 , 20.4088637 , 15.1077663 ,
       15.1077663 , 15.1077663 ])

In [70]:
# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y5_test, y5_pred))

# Calculate the MAE
mae = mean_absolute_error(y5_test, y5_pred)

# Calculate R-squared
r2 = r2_score(y5_test, y5_pred)

#MAPE
mape = mean_absolute_error(y5_test, y5_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 6.727211469788097
MAE: 5.436972481800313
R-squared: -0.044966693194536944
MAPE: 543.6972481800314


In [36]:
X = df2.iloc[:, -6]
y5 = df2.iloc[:, -5]
X_train, X_test, y5_train, y5_test = train_test_split(X, y5, test_size=0.1, random_state=0)

regressor = RandomForestRegressor(random_state=0)

param_grid = {'n_estimators': [100, 200, 300],
              'max_depth': [4, 6, 8],
              'min_samples_split': [2, 4, 6],
              'min_samples_leaf': [1, 2, 4],
              'bootstrap': [True],
              'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              #'min_weight_fraction_leaf': [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_features' : ['sqrt', 'log2', None],
              #'max_leaf_nodes' : [1, 2, 4],
              #'min_impurity_decrease' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              #'oob_score' : [True, False],
              #'n_jobs' : [-2, -1, 0, 1, 2],
              #'verbose' : [0, 2, 4, 6, 8],
              'warm_start' : [False],
              #'ccp_alpha' : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
              'max_samples' : [0, 1, 2, 3, 4, 5, 6, 7]
             }

scoring = 'neg_mean_absolute_error'

grid_search = GridSearchCV(estimator=regressor, param_grid=param_grid, scoring=scoring, cv=5, n_jobs=-1)
grid_search.fit(X_train, y5_train)

print("Best parameters found: ",grid_search.best_params_)
print("Best score found: ",grid_search.best_score_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [nan nan nan ... nan nan nan]
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[114.74197  119.99893  113.5441   117.52787  121.31142  106.575165
 119.25155  100.8682   116.75976  123.445    118.1406   118.62136
 113.40339  129.46445  121.82467  114.3169   116.80065  117.8094
 112.222244 123.75831  114.545105 129.0951   118.83052  116.73993
 108.465    109.392265 125.18107  117.10937  107.04534  118.839935
 130.39027  119.05653  118.55764  123.412766 127.37537  104.724365
 117.62161  119.530106 108.8787   112.222244 113.8974   124.12203
 125.91973  117.3694   124.55364  128.0729   111.75394  117.9483
 116.46277  120.54352  111.33217  117.1762   118.839935 129.79053
 120.56157  114.14003  129.797    111.08917  119.5569   113.33254
 115.146126 125.19597  111.4765   110.87929  103.71453  107.2831
 135.24107  118.38325  116.35641  114.09143  119.4351   121.23691
 119.95013  116.19984  115.6637   124.61943  112.9381   119.4887
 125.86369  121.69771  120.87006  124.43464  114.19293  119.74674
 136.6577   109.531    119.70153  106.88413  129.60167  107.25937
 116.5859   120.21944  114.6972   127.57422  114.98728  118.057434
 121.437225 128.73323  114.88087  118.839935 117.0302   110.770164
 123.06897  113.377266 110.93541  113.55706  113.08551  114.63424
 113.243965 115.98005  120.88489  122.63613  125.11807  116.176735
 108.789276 116.19984  109.67253  120.68543  125.6613   124.12203
 117.72873  114.173065 120.3433   115.42109  132.69374  126.5718
 115.61728  127.51463  108.52341  124.6354   113.84026  119.91463
 134.592    108.465    123.537964 108.2361   106.1047   119.970436
 116.585335 127.6365   123.9076   127.571655 114.17157  111.20313
 122.8869   134.06047  122.841    116.69932  115.2727   127.182335
 118.38325  124.87677 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [37]:
best_model = grid_search.best_estimator_
y5_pred = best_model.predict(X_test)
y5_pred

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [38]:
# Calculate R-squared
r2 = r2_score(y5_test, y5_pred)

#MAPE
mape = mean_absolute_error(y5_test, y5_pred)*100


# Print the results
print("RMSE:", rmse)
print("MAE:", mae)
print('R-squared:', r2)
print('MAPE:' , mape)

RMSE: 7.033367519715778
MAE: 5.367928104575163
R-squared: -0.14224406798310496
MAPE: 536.7928104575162
